pipeline {
    agent any

    environment {
        APP_DIR = "../whanos-app"
        DOCKER_REGISTRY = "us-central1-docker.pkg.dev/whanos-443406/whanos"
        APP_NAME = "whanos-app"
    }

    options {
        pollSCM('H H * * *')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: 'github-pat', url: 'https://github.com/EpitechPromo2027/B-DOP-500-PAR-5-1-whanos-johana.gaba.git'
            }
        }

        stage('Detect Language') {
            steps {
                sh '''
                chmod +x scripts/detect_lang.sh
                ./scripts/detect_lang.sh > language.txt
                '''
            }
        }

        stage('Copy Dockerfile') {
            steps {
                sh '''
                chmod +x scripts/copy_dockerfile.sh
                ./scripts/copy_dockerfile.sh
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                sh '''
                chmod +x scripts/build_and_push.sh
                ./build_and_push.sh
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
