pipeline {
    agent any

    environment {
        DOCKER_REGISTRY = "us-central1-docker.pkg.dev/whanos-443406/whanos"
        KUBECONFIG = credentials('kubeconfig-credential')
    }

    triggers {
        pollSCM('H H * * *') 
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', credentialsId: 'github-pat', url: 'https://github.com/yasssb/test-whanos-C.git'
            }
        }

        stage('Detect Language') {
            steps {
                sh '''
                chmod +x jenkins-pipeline/scripts/detect_lang.sh
                ./scripts/detect_lang.sh > language.txt
                '''
            }
        }

        stage('Copy Dockerfile') {
            steps {
                sh '''
                chmod +x jenkins-pipeline/scripts/copy_dockerfile.sh
                ./scripts/copy_dockerfile.sh
                '''
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                sh '''
                chmod +x jenkins-pipeline/scripts/build_and_push.sh
                ./scripts/build_and_push.sh
                '''
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}
